version: '3'
services:
  backend:
    container_name: backend
    image: getjv/php7.2
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - HTTPD_SERVER_NAME=local
      - HTTPD_DOCUMENT_ROOT_CONTEXT=public
    links:
      - mysql
  mysql:
    container_name: mysql
    image: getjv/mysql
    restart: always
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=mysql

      

     
     